### ISSUE TITLE
HUD好卡hhh

### ISSUE THREAD

**Issue by qznfbnj** [AutomaticalEchoes/equipsuit#3]
1.19.2-Forge_43.3.2
这个HUD好卡哈哈，怪不得会有简易模式hhh
## renderAll
https://spark.lucko.me/xsZtXQpewD
![image](https://github.com/AutomaticalEchoes/equipsuit/assets/100760086/4747591b-86d9-4bc5-908a-47e22e39e286)
![image](https://github.com/AutomaticalEchoes/equipsuit/assets/100760086/35579c65-da92-40ac-892a-b9942cfea210)
### switch F1
![image](https://github.com/AutomaticalEchoes/equipsuit/assets/100760086/68608e87-7d34-4aec-befe-a4bb497a50d9)
## renderSimple
https://spark.lucko.me/tjK9mJnKbD
![image](https://github.com/AutomaticalEchoes/equipsuit/assets/100760086/6e13882f-3331-47a6-9685-08e4adab49fe)
![image](https://github.com/AutomaticalEchoes/equipsuit/assets/100760086/342af138-7f4f-44b6-ab22-624dd1f24a37)

**Comment by AutomaticalEchoes** [comment]
@qznfbnj 我看一哈，确实对性能优化不熟，而且这个Mod确实较早时候写的，我也忘了我干了什么蠢事。

**Comment by qznfbnj** [comment]
还有这个简易模式的位置……挺微妙的，不过这楼不是最小实例测试，仅供参考
### 3x 非最大化
![image](https://github.com/AutomaticalEchoes/equipsuit/assets/100760086/8905f7d0-7384-4806-b9e3-352664a69c60)
### 3x 最大化
![image](https://github.com/AutomaticalEchoes/equipsuit/assets/100760086/8e44b411-7c5a-4145-b432-a570b54717fb)
### 4x 最大化
![image](https://github.com/AutomaticalEchoes/equipsuit/assets/100760086/78ecb731-5c05-4dfe-b926-dea81fe6fbcf)

**Comment by AutomaticalEchoes** [comment]
@qznfbnj 简易模式确实有问题，我的本地项目已经修复了，但我打算重绘，因为原来这个hud本质是个toolTip,在不同版本下表现都有差距，尤其1.19到1.20期间，渲染一直在改。

**Comment by AutomaticalEchoes** [comment]
@qznfbnj 
     我于1.8.2版本中重绘了简易模式的hud并修正了位置异常的BUG。
     同时根据你反馈的图片，我发现HUD渲染占用过高的原因并将其修复，因为这个HUD不应该悬浮在F3的调试HUD之上，具体原因是由于早期开发时缺乏查看ForgeEvent运行机制的习惯，照猫画虎在一个Forge提供的GuiEvent中绘制了自己的GUI，但实际上Forge每画一个GUI都会触发一次这个Event，其次这个Event是一个父类，其还有Pre（绘制之前）、Post（绘制时）两个子类。 简而言之，有多少个Hud在绘制，我这个Hud就绘制多少遍，而且是超级加倍。
    现在指定在HotBar（也就是快捷物品栏）绘制之后绘制本模组的HUD。
    我还修改了信息同步的数据类型，之前同步时是直接传NBT，调用时（大部分时候就是绘制，结合上面的超级加倍）再解析（FromJson）。现在同步完会直接解析并生成对象，调用时直接调用对象不会再解析了。

**Comment by AutomaticalEchoes** [comment]
相关版本下载已同步到到OneDrive和百科
感谢使用和反馈，不出意外这个issue将在1周后关闭

**Comment by qznfbnj** [comment]
1.8.2 两种模式性能没什么差别了，看来简易模式只是外观简易，不是为了性能分出来的w
