### ISSUE TITLE
与 ImmediatelyFast 一起使用时的渲染问题

### ISSUE THREAD

**Issue by qznfbnj** [AutomaticalEchoes/equipsuit#4]
如果是 ImmediatelyFast 的问题，我会转发到他们的问题追踪器。
## 模组列表
![image](https://github.com/AutomaticalEchoes/equipsuit/assets/100760086/9dd807e0-1376-44ed-8b60-17e7cd59bfc0)
### 本模组的HUD（简易模式）看起来没什么问题，字体渲染也正常
![image](https://github.com/AutomaticalEchoes/equipsuit/assets/100760086/a5bb379d-8dda-4cd7-b0d6-ec7a4df1c9d3)
### HUD（非简易模式）无法正常渲染；字体渲染不正常，比如F3调试界面、字幕等
![image](https://github.com/AutomaticalEchoes/equipsuit/assets/100760086/fdd38f8e-cf11-43bd-bd84-50aeae1f2eaf)
![image](https://github.com/AutomaticalEchoes/equipsuit/assets/100760086/6f891dd0-5bec-445e-a0fa-6321a461dd0a)
### 关闭 ImmediatelyFast 的 hud_batching 后，HUD（非简易模式）正常了
![image](https://github.com/AutomaticalEchoes/equipsuit/assets/100760086/52ca463e-4756-421d-b64e-0b2d521de0cd)
678

**Comment by AutomaticalEchoes** [comment]
@qznfbnj 我更新至1.8.2后在Forge1.19.2环境下与ImmediatelyFast的默认配置下（hud_batching是true)运行，没有复现这个BUG.
我判断这个问题的本质其实是透明度太低，一如我在另一个issue中提到旧版本的渲染频率问题，当时透明度的设置也是以实际为基准的。因为高频渲染导致的渲染叠加，早期开发时设置透明度为10%时我的HUD依然非常亮。所以当时透明度后移了一位。也就是80%实际在后台运行的透明度是8%。ImmediatelyFast优化Hud渲染降低了我的HUD的渲染重叠频率，因而透明度回归到最真实的8% ，在1.8.2修复后的测试中，透明度低于10%基本是看不见的。
