### ISSUE TITLE
加入自行增加模组的BMC3包后，进入世界崩溃

### ISSUE THREAD

**Issue by qznfbnj** [AutomaticalEchoes/equipsuit#5]
先把这问题放在这，更详细的测试后面再补充（二分法查找冲突的模组，查找失败，就很复杂了）
![image](https://github.com/AutomaticalEchoes/equipsuit/assets/100760086/467d9efb-8e85-443c-882f-bac834caad29)
[crash-2023-11-14_22.11.50-server.txt](https://gist.github.com/qznfbnj/1b87d9fe050a389b091c594069350834#file-crash-2023-11-14_22-11-50-server-txt)
[debug.log](https://gist.github.com/qznfbnj/e04930012ffea2df486d805173a0e0b7#file-debug-log)（[文件版](https://github.com/AutomaticalEchoes/equipsuit/files/13349779/debug.log)）
[latest.log](https://gist.github.com/qznfbnj/6f3baf239cd5c483436943443349011e#file-latest-log)（[文件版](https://github.com/AutomaticalEchoes/equipsuit/files/13349782/latest.log)）
[错误报告-2023-11-14_22.28.24.zip](https://github.com/AutomaticalEchoes/equipsuit/files/13349896/-2023-11-14_22.28.24.zip)

**Comment by AutomaticalEchoes** [comment]
@qznfbnj 模组兼容问题有些时候不是我单方面能解决的，另外反馈时请尽可能补全全名称。
如果你的BMC是指BetterMC。我在HMCL启动器、forge1.19.2 版本下将其与本模组的1.8.2一起运行是可以成功进入没有问题的。
但是我在未正式公开的发布的1.8.1版本中更改了一个mixin的命名，可能旧版本的mixin命名与整合包产生了某些错误。

**Comment by qznfbnj** [comment]
不急，只是粗略的二分查找失败了，而现在又没空详细测试，如果有空闲了我会慢慢试什么组合会产生问题

Edit：其实一楼说的二分查找失败就是：bmc原生模组+equipsort没问题，自行增加模组（+它们的前置）+equipsort也没问题，是这么一个“失败”哈哈

**Comment by AutomaticalEchoes** [comment]
@建议使用最新的1.8.2版本测试。Mixins真的的冲突的万恶之源。

**Comment by qznfbnj** [comment]
好的，自行增加模组的BMC3包中，使用1.8.2不会崩溃。
关闭这个问题，在未来可能会找出使用1.8.0时什么组合有问题并留下评论，但不会Reopen此问题。
